// Mocks generated by Mockito 5.4.6 from annotations
// in farm_pro/test/sms_sales_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;

import 'package:farm_pro/models/models.dart' as _i6;
import 'package:farm_pro/services/settings_service.dart' as _i5;
import 'package:farm_pro/services/sms_service.dart' as _i4;
import 'package:flutter_background_messenger/flutter_background_messenger.dart'
    as _i2;
import 'package:get/get.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterBackgroundMessenger_0 extends _i1.SmartFake
    implements _i2.FlutterBackgroundMessenger {
  _FakeFlutterBackgroundMessenger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_2 extends _i1.SmartFake implements _i3.RxInt {
  _FakeRxInt_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSmsService_4 extends _i1.SmartFake implements _i4.SmsService {
  _FakeSmsService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_5<T> extends _i1.SmartFake implements _i3.Rx<T> {
  _FakeRx_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxDouble_6 extends _i1.SmartFake implements _i3.RxDouble {
  _FakeRxDouble_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_7 extends _i1.SmartFake
    implements _i5.SettingsService {
  _FakeSettingsService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemSettings_8 extends _i1.SmartFake
    implements _i6.SystemSettings {
  _FakeSystemSettings_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SmsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmsService extends _i1.Mock implements _i4.SmsService {
  MockSmsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterBackgroundMessenger get messenger =>
      (super.noSuchMethod(
            Invocation.getter(#messenger),
            returnValue: _FakeFlutterBackgroundMessenger_0(
              this,
              Invocation.getter(#messenger),
            ),
          )
          as _i2.FlutterBackgroundMessenger);

  @override
  _i3.RxBool get isSmsAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isSmsAvailable),
            returnValue: _FakeRxBool_1(
              this,
              Invocation.getter(#isSmsAvailable),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxInt get totalSmsSent =>
      (super.noSuchMethod(
            Invocation.getter(#totalSmsSent),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalSmsSent)),
          )
          as _i3.RxInt);

  @override
  _i3.RxInt get totalSmsFailed =>
      (super.noSuchMethod(
            Invocation.getter(#totalSmsFailed),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalSmsFailed)),
          )
          as _i3.RxInt);

  @override
  _i3.RxInt get smsQueueSize =>
      (super.noSuchMethod(
            Invocation.getter(#smsQueueSize),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#smsQueueSize)),
          )
          as _i3.RxInt);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<_i4.SmsService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<_i4.SmsService>.value(
              _FakeSmsService_4(this, Invocation.method(#init, [])),
            ),
          )
          as _i7.Future<_i4.SmsService>);

  @override
  _i7.Future<void> initializeSmsService() =>
      (super.noSuchMethod(
            Invocation.method(#initializeSmsService, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> checkSmsPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkSmsPermission, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> forceRestart() =>
      (super.noSuchMethod(
            Invocation.method(#forceRestart, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  String? validateKenyanPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#validateKenyanPhoneNumber, [phoneNumber]),
          )
          as String?);

  @override
  void queueSms(
    String? phoneNumber,
    String? message, {
    int? maxRetries = 3,
    int? priority = 1,
  }) => super.noSuchMethod(
    Invocation.method(
      #queueSms,
      [phoneNumber, message],
      {#maxRetries: maxRetries, #priority: priority},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> sendDirectSms(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendDirectSms, [phoneNumber, message]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendSmsViaGateway(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendSmsViaGateway, [phoneNumber, message]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendSms(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendSms, [phoneNumber, message]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendSmsRobust(
    String? phoneNumber,
    String? message, {
    int? maxRetries = 3,
    int? priority = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendSmsRobust,
              [phoneNumber, message],
              {#maxRetries: maxRetries, #priority: priority},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> sendCoffeeCollectionSMS(_i6.CoffeeCollection? collection) =>
      (super.noSuchMethod(
            Invocation.method(#sendCoffeeCollectionSMS, [collection]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>> runSmsDiagnostic(String? testPhoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#runSmsDiagnostic, [testPhoneNumber]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> getSmsStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getSmsStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearSmsQueue() => super.noSuchMethod(
    Invocation.method(#clearSmsQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSmsStatistics() => super.noSuchMethod(
    Invocation.method(#resetSmsStatistics, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> testSmsSending() =>
      (super.noSuchMethod(
            Invocation.method(#testSmsSending, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i5.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Rx<_i6.OrganizationSettings> get organizationSettings =>
      (super.noSuchMethod(
            Invocation.getter(#organizationSettings),
            returnValue: _FakeRx_5<_i6.OrganizationSettings>(
              this,
              Invocation.getter(#organizationSettings),
            ),
          )
          as _i3.Rx<_i6.OrganizationSettings>);

  @override
  _i3.Rx<_i6.SystemSettings> get systemSettings =>
      (super.noSuchMethod(
            Invocation.getter(#systemSettings),
            returnValue: _FakeRx_5<_i6.SystemSettings>(
              this,
              Invocation.getter(#systemSettings),
            ),
          )
          as _i3.Rx<_i6.SystemSettings>);

  @override
  _i3.RxDouble get defaultTareWeight =>
      (super.noSuchMethod(
            Invocation.getter(#defaultTareWeight),
            returnValue: _FakeRxDouble_6(
              this,
              Invocation.getter(#defaultTareWeight),
            ),
          )
          as _i3.RxDouble);

  @override
  _i7.Stream<double> get tareWeightStream =>
      (super.noSuchMethod(
            Invocation.getter(#tareWeightStream),
            returnValue: _i7.Stream<double>.empty(),
          )
          as _i7.Stream<double>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<_i5.SettingsService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<_i5.SettingsService>.value(
              _FakeSettingsService_7(this, Invocation.method(#init, [])),
            ),
          )
          as _i7.Future<_i5.SettingsService>);

  @override
  _i7.Future<void> updateOrganizationSettings(
    _i6.OrganizationSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganizationSettings, [settings]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateSystemSettings(_i6.SystemSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#updateSystemSettings, [settings]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateDefaultTareWeight(double? newTareWeight) =>
      (super.noSuchMethod(
            Invocation.method(#updateDefaultTareWeight, [newTareWeight]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, String> validateSmsGatewayConfig(_i6.SystemSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#validateSmsGatewayConfig, [settings]),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool isSmsGatewayConfigured() =>
      (super.noSuchMethod(
            Invocation.method(#isSmsGatewayConfigured, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<Map<String, String>> updateSmsGatewayConfig({
    required bool? enabled,
    required String? url,
    required String? username,
    required String? password,
    required String? senderId,
    required String? apiKey,
    required bool? fallbackToSim,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSmsGatewayConfig, [], {
              #enabled: enabled,
              #url: url,
              #username: username,
              #password: password,
              #senderId: senderId,
              #apiKey: apiKey,
              #fallbackToSim: fallbackToSim,
            }),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<Map<String, String?>> getSmsGatewayCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getSmsGatewayCredentials, []),
            returnValue: _i7.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i7.Future<Map<String, String?>>);

  @override
  _i7.Future<_i6.SystemSettings> getCompleteSystemSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getCompleteSystemSettings, []),
            returnValue: _i7.Future<_i6.SystemSettings>.value(
              _FakeSystemSettings_8(
                this,
                Invocation.method(#getCompleteSystemSettings, []),
              ),
            ),
          )
          as _i7.Future<_i6.SystemSettings>);

  @override
  _i7.Future<String?> saveOrganizationLogo(_i8.File? logoFile) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrganizationLogo, [logoFile]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [key]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetting, [key, value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
