// Mocks generated by Mockito 5.4.6 from annotations
// in farm_pro/test/sms_sales_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i9;
import 'dart:ui' as _i12;

import 'package:farm_pro/controllers/inventory_controller.dart' as _i10;
import 'package:farm_pro/controllers/member_controller.dart' as _i13;
import 'package:farm_pro/models/models.dart' as _i6;
import 'package:farm_pro/services/services.dart' as _i4;
import 'package:farm_pro/services/settings_service.dart' as _i5;
import 'package:flutter/material.dart' as _i7;
import 'package:flutter_background_messenger/flutter_background_messenger.dart'
    as _i2;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterBackgroundMessenger_0 extends _i1.SmartFake
    implements _i2.FlutterBackgroundMessenger {
  _FakeFlutterBackgroundMessenger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_2 extends _i1.SmartFake implements _i3.RxInt {
  _FakeRxInt_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSmsService_4 extends _i1.SmartFake implements _i4.SmsService {
  _FakeSmsService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_5<T> extends _i1.SmartFake implements _i3.Rx<T> {
  _FakeRx_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxDouble_6 extends _i1.SmartFake implements _i3.RxDouble {
  _FakeRxDouble_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsService_7 extends _i1.SmartFake
    implements _i5.SettingsService {
  _FakeSettingsService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemSettings_8 extends _i1.SmartFake
    implements _i6.SystemSettings {
  _FakeSystemSettings_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_9 extends _i1.SmartFake implements _i3.RxString {
  _FakeRxString_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_10 extends _i1.SmartFake
    implements _i7.TextEditingController {
  _FakeTextEditingController_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_11<E> extends _i1.SmartFake implements _i3.RxList<E> {
  _FakeRxList_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_12 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_13 extends _i1.SmartFake implements _i6.User {
  _FakeUser_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SmsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmsService extends _i1.Mock implements _i4.SmsService {
  MockSmsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterBackgroundMessenger get messenger =>
      (super.noSuchMethod(
            Invocation.getter(#messenger),
            returnValue: _FakeFlutterBackgroundMessenger_0(
              this,
              Invocation.getter(#messenger),
            ),
          )
          as _i2.FlutterBackgroundMessenger);

  @override
  _i3.RxBool get isSmsAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isSmsAvailable),
            returnValue: _FakeRxBool_1(
              this,
              Invocation.getter(#isSmsAvailable),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxInt get totalSmsSent =>
      (super.noSuchMethod(
            Invocation.getter(#totalSmsSent),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalSmsSent)),
          )
          as _i3.RxInt);

  @override
  _i3.RxInt get totalSmsFailed =>
      (super.noSuchMethod(
            Invocation.getter(#totalSmsFailed),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalSmsFailed)),
          )
          as _i3.RxInt);

  @override
  _i3.RxInt get smsQueueSize =>
      (super.noSuchMethod(
            Invocation.getter(#smsQueueSize),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#smsQueueSize)),
          )
          as _i3.RxInt);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i4.SmsService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i4.SmsService>.value(
              _FakeSmsService_4(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i4.SmsService>);

  @override
  _i8.Future<void> initializeSmsService() =>
      (super.noSuchMethod(
            Invocation.method(#initializeSmsService, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> checkSmsPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkSmsPermission, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> forceRestart() =>
      (super.noSuchMethod(
            Invocation.method(#forceRestart, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String? validateKenyanPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#validateKenyanPhoneNumber, [phoneNumber]),
          )
          as String?);

  @override
  void queueSms(
    String? phoneNumber,
    String? message, {
    int? maxRetries = 3,
    int? priority = 1,
  }) => super.noSuchMethod(
    Invocation.method(
      #queueSms,
      [phoneNumber, message],
      {#maxRetries: maxRetries, #priority: priority},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> sendDirectSms(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendDirectSms, [phoneNumber, message]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> sendSmsViaGateway(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendSmsViaGateway, [phoneNumber, message]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> sendSms(String? phoneNumber, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendSms, [phoneNumber, message]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> sendSmsRobust(
    String? phoneNumber,
    String? message, {
    int? maxRetries = 3,
    int? priority = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendSmsRobust,
              [phoneNumber, message],
              {#maxRetries: maxRetries, #priority: priority},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> sendCoffeeCollectionSMS(_i6.CoffeeCollection? collection) =>
      (super.noSuchMethod(
            Invocation.method(#sendCoffeeCollectionSMS, [collection]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> runSmsDiagnostic(String? testPhoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#runSmsDiagnostic, [testPhoneNumber]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> getSmsStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getSmsStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearSmsQueue() => super.noSuchMethod(
    Invocation.method(#clearSmsQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSmsStatistics() => super.noSuchMethod(
    Invocation.method(#resetSmsStatistics, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> testSmsSending() =>
      (super.noSuchMethod(
            Invocation.method(#testSmsSending, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i5.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Rx<_i6.OrganizationSettings> get organizationSettings =>
      (super.noSuchMethod(
            Invocation.getter(#organizationSettings),
            returnValue: _FakeRx_5<_i6.OrganizationSettings>(
              this,
              Invocation.getter(#organizationSettings),
            ),
          )
          as _i3.Rx<_i6.OrganizationSettings>);

  @override
  _i3.Rx<_i6.SystemSettings> get systemSettings =>
      (super.noSuchMethod(
            Invocation.getter(#systemSettings),
            returnValue: _FakeRx_5<_i6.SystemSettings>(
              this,
              Invocation.getter(#systemSettings),
            ),
          )
          as _i3.Rx<_i6.SystemSettings>);

  @override
  _i3.RxDouble get defaultTareWeight =>
      (super.noSuchMethod(
            Invocation.getter(#defaultTareWeight),
            returnValue: _FakeRxDouble_6(
              this,
              Invocation.getter(#defaultTareWeight),
            ),
          )
          as _i3.RxDouble);

  @override
  _i8.Stream<double> get tareWeightStream =>
      (super.noSuchMethod(
            Invocation.getter(#tareWeightStream),
            returnValue: _i8.Stream<double>.empty(),
          )
          as _i8.Stream<double>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i5.SettingsService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i5.SettingsService>.value(
              _FakeSettingsService_7(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i5.SettingsService>);

  @override
  _i8.Future<void> updateOrganizationSettings(
    _i6.OrganizationSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganizationSettings, [settings]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSystemSettings(_i6.SystemSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#updateSystemSettings, [settings]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateDefaultTareWeight(double? newTareWeight) =>
      (super.noSuchMethod(
            Invocation.method(#updateDefaultTareWeight, [newTareWeight]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, String> validateSmsGatewayConfig(_i6.SystemSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#validateSmsGatewayConfig, [settings]),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool isSmsGatewayConfigured() =>
      (super.noSuchMethod(
            Invocation.method(#isSmsGatewayConfigured, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<Map<String, String>> updateSmsGatewayConfig({
    required bool? enabled,
    required String? url,
    required String? username,
    required String? password,
    required String? senderId,
    required String? apiKey,
    required bool? fallbackToSim,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSmsGatewayConfig, [], {
              #enabled: enabled,
              #url: url,
              #username: username,
              #password: password,
              #senderId: senderId,
              #apiKey: apiKey,
              #fallbackToSim: fallbackToSim,
            }),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<Map<String, String?>> getSmsGatewayCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getSmsGatewayCredentials, []),
            returnValue: _i8.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i8.Future<Map<String, String?>>);

  @override
  _i8.Future<_i6.SystemSettings> getCompleteSystemSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getCompleteSystemSettings, []),
            returnValue: _i8.Future<_i6.SystemSettings>.value(
              _FakeSystemSettings_8(
                this,
                Invocation.method(#getCompleteSystemSettings, []),
              ),
            ),
          )
          as _i8.Future<_i6.SystemSettings>);

  @override
  _i8.Future<String?> saveOrganizationLogo(_i9.File? logoFile) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrganizationLogo, [logoFile]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [key]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> saveSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetting, [key, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InventoryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryController extends _i1.Mock
    implements _i10.InventoryController {
  MockInventoryController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoading)),
          )
          as _i3.RxBool);

  @override
  _i3.RxString get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _FakeRxString_9(this, Invocation.getter(#error)),
          )
          as _i3.RxString);

  @override
  _i7.TextEditingController get productNameController =>
      (super.noSuchMethod(
            Invocation.getter(#productNameController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#productNameController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get productDescriptionController =>
      (super.noSuchMethod(
            Invocation.getter(#productDescriptionController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#productDescriptionController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get packSizeController =>
      (super.noSuchMethod(
            Invocation.getter(#packSizeController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#packSizeController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get salesPriceController =>
      (super.noSuchMethod(
            Invocation.getter(#salesPriceController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#salesPriceController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get costPriceController =>
      (super.noSuchMethod(
            Invocation.getter(#costPriceController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#costPriceController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get minimumStockController =>
      (super.noSuchMethod(
            Invocation.getter(#minimumStockController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#minimumStockController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get maximumStockController =>
      (super.noSuchMethod(
            Invocation.getter(#maximumStockController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#maximumStockController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get barcodeController =>
      (super.noSuchMethod(
            Invocation.getter(#barcodeController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#barcodeController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get skuController =>
      (super.noSuchMethod(
            Invocation.getter(#skuController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#skuController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i3.Rx<_i6.ProductCategory?> get selectedCategory =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCategory),
            returnValue: _FakeRx_5<_i6.ProductCategory?>(
              this,
              Invocation.getter(#selectedCategory),
            ),
          )
          as _i3.Rx<_i6.ProductCategory?>);

  @override
  _i3.Rx<_i6.UnitOfMeasure?> get selectedUnit =>
      (super.noSuchMethod(
            Invocation.getter(#selectedUnit),
            returnValue: _FakeRx_5<_i6.UnitOfMeasure?>(
              this,
              Invocation.getter(#selectedUnit),
            ),
          )
          as _i3.Rx<_i6.UnitOfMeasure?>);

  @override
  _i3.RxBool get allowPartialSales =>
      (super.noSuchMethod(
            Invocation.getter(#allowPartialSales),
            returnValue: _FakeRxBool_1(
              this,
              Invocation.getter(#allowPartialSales),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxBool get canBeSplit =>
      (super.noSuchMethod(
            Invocation.getter(#canBeSplit),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#canBeSplit)),
          )
          as _i3.RxBool);

  @override
  _i3.RxList<_i6.SaleItem> get saleItems =>
      (super.noSuchMethod(
            Invocation.getter(#saleItems),
            returnValue: _FakeRxList_11<_i6.SaleItem>(
              this,
              Invocation.getter(#saleItems),
            ),
          )
          as _i3.RxList<_i6.SaleItem>);

  @override
  _i3.Rx<_i6.Member?> get selectedMember =>
      (super.noSuchMethod(
            Invocation.getter(#selectedMember),
            returnValue: _FakeRx_5<_i6.Member?>(
              this,
              Invocation.getter(#selectedMember),
            ),
          )
          as _i3.Rx<_i6.Member?>);

  @override
  _i3.RxString get saleType =>
      (super.noSuchMethod(
            Invocation.getter(#saleType),
            returnValue: _FakeRxString_9(this, Invocation.getter(#saleType)),
          )
          as _i3.RxString);

  @override
  _i7.TextEditingController get paidAmountController =>
      (super.noSuchMethod(
            Invocation.getter(#paidAmountController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#paidAmountController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i7.TextEditingController get saleNotesController =>
      (super.noSuchMethod(
            Invocation.getter(#saleNotesController),
            returnValue: _FakeTextEditingController_10(
              this,
              Invocation.getter(#saleNotesController),
            ),
          )
          as _i7.TextEditingController);

  @override
  _i3.RxDouble get totalAmount =>
      (super.noSuchMethod(
            Invocation.getter(#totalAmount),
            returnValue: _FakeRxDouble_6(this, Invocation.getter(#totalAmount)),
          )
          as _i3.RxDouble);

  @override
  _i3.RxList<double> get packSizes =>
      (super.noSuchMethod(
            Invocation.getter(#packSizes),
            returnValue: _FakeRxList_11<double>(
              this,
              Invocation.getter(#packSizes),
            ),
          )
          as _i3.RxList<double>);

  @override
  List<_i6.UnitOfMeasure> get units =>
      (super.noSuchMethod(
            Invocation.getter(#units),
            returnValue: <_i6.UnitOfMeasure>[],
          )
          as List<_i6.UnitOfMeasure>);

  @override
  List<_i6.ProductCategory> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i6.ProductCategory>[],
          )
          as List<_i6.ProductCategory>);

  @override
  List<_i6.Product> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: <_i6.Product>[],
          )
          as List<_i6.Product>);

  @override
  List<_i6.Stock> get stocks =>
      (super.noSuchMethod(
            Invocation.getter(#stocks),
            returnValue: <_i6.Stock>[],
          )
          as List<_i6.Stock>);

  @override
  List<_i6.Sale> get sales =>
      (super.noSuchMethod(Invocation.getter(#sales), returnValue: <_i6.Sale>[])
          as List<_i6.Sale>);

  @override
  List<_i6.Repayment> get repayments =>
      (super.noSuchMethod(
            Invocation.getter(#repayments),
            returnValue: <_i6.Repayment>[],
          )
          as List<_i6.Repayment>);

  @override
  List<_i6.Sale> get creditSales =>
      (super.noSuchMethod(
            Invocation.getter(#creditSales),
            returnValue: <_i6.Sale>[],
          )
          as List<_i6.Sale>);

  @override
  List<_i6.Product> get lowStockProducts =>
      (super.noSuchMethod(
            Invocation.getter(#lowStockProducts),
            returnValue: <_i6.Product>[],
          )
          as List<_i6.Product>);

  @override
  List<_i6.Product> get outOfStockProducts =>
      (super.noSuchMethod(
            Invocation.getter(#outOfStockProducts),
            returnValue: <_i6.Product>[],
          )
          as List<_i6.Product>);

  @override
  double get totalStockValue =>
      (super.noSuchMethod(Invocation.getter(#totalStockValue), returnValue: 0.0)
          as double);

  @override
  Map<String, int> get categoryProductCounts =>
      (super.noSuchMethod(
            Invocation.getter(#categoryProductCounts),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshInventoryData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshInventoryData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadAllInventoryData() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllInventoryData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> addProduct() =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> adjustStock({
    required String? productId,
    required double? quantity,
    required String? movementType,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #quantity: quantity,
              #movementType: movementType,
              #notes: notes,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void addSaleItem(
    _i6.Product? product,
    double? quantity,
    double? packSizeSold,
  ) => super.noSuchMethod(
    Invocation.method(#addSaleItem, [product, quantity, packSizeSold]),
    returnValueForMissingStub: null,
  );

  @override
  void removeSaleItem(int? index) => super.noSuchMethod(
    Invocation.method(#removeSaleItem, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSaleItemQuantity(int? index, double? quantity) =>
      super.noSuchMethod(
        Invocation.method(#updateSaleItemQuantity, [index, quantity]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> createSale() =>
      (super.noSuchMethod(
            Invocation.method(#createSale, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i6.Stock? getProductStock(String? productId) =>
      (super.noSuchMethod(Invocation.method(#getProductStock, [productId]))
          as _i6.Stock?);

  @override
  double getMemberTotalCredit(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberTotalCredit, [memberId]),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i6.Sale> getMemberCreditSales(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberCreditSales, [memberId]),
            returnValue: <_i6.Sale>[],
          )
          as List<_i6.Sale>);

  @override
  void showProductForm() => super.noSuchMethod(
    Invocation.method(#showProductForm, []),
    returnValueForMissingStub: null,
  );

  @override
  void showSaleForm() => super.noSuchMethod(
    Invocation.method(#showSaleForm, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSaleType(String? type) => super.noSuchMethod(
    Invocation.method(#setSaleType, [type]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedMember(_i6.Member? member) => super.noSuchMethod(
    Invocation.method(#setSelectedMember, [member]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedCategory(_i6.ProductCategory? category) => super.noSuchMethod(
    Invocation.method(#setSelectedCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedUnit(_i6.UnitOfMeasure? unit) => super.noSuchMethod(
    Invocation.method(#setSelectedUnit, [unit]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> deleteCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [categoryId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> canDeleteCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#canDeleteCategory, [categoryId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i6.Product>> getProductsInCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsInCategory, [categoryId]),
            returnValue: _i8.Future<List<_i6.Product>>.value(<_i6.Product>[]),
          )
          as _i8.Future<List<_i6.Product>>);

  @override
  _i8.Future<bool> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> canDeleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#canDeleteProduct, [productId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getProductSalesHistory(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSalesHistory, [productId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<_i6.StockMovement>> getStockMovements(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getStockMovements, [productId]),
            returnValue: _i8.Future<List<_i6.StockMovement>>.value(
              <_i6.StockMovement>[],
            ),
          )
          as _i8.Future<List<_i6.StockMovement>>);

  @override
  _i8.Future<bool> splitProduct({
    required String? productId,
    required double? splitSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#splitProduct, [], {
              #productId: productId,
              #splitSize: splitSize,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i6.Product>> getSplitProducts(String? parentProductId) =>
      (super.noSuchMethod(
            Invocation.method(#getSplitProducts, [parentProductId]),
            returnValue: _i8.Future<List<_i6.Product>>.value(<_i6.Product>[]),
          )
          as _i8.Future<List<_i6.Product>>);

  @override
  _i8.Future<bool> hasBeenSplit(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#hasBeenSplit, [productId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void addPackSize(double? size) => super.noSuchMethod(
    Invocation.method(#addPackSize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  void removePackSize(double? size) => super.noSuchMethod(
    Invocation.method(#removePackSize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Disposer addListener(_i11.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i11.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i12.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Disposer addListenerId(Object? key, _i11.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i11.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MemberController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberController extends _i1.Mock implements _i13.MemberController {
  MockMemberController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RxList<_i6.Member> get members =>
      (super.noSuchMethod(
            Invocation.getter(#members),
            returnValue: _FakeRxList_11<_i6.Member>(
              this,
              Invocation.getter(#members),
            ),
          )
          as _i3.RxList<_i6.Member>);

  @override
  List<_i6.Member> get activeMembers =>
      (super.noSuchMethod(
            Invocation.getter(#activeMembers),
            returnValue: <_i6.Member>[],
          )
          as List<_i6.Member>);

  @override
  _i3.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoading)),
          )
          as _i3.RxBool);

  @override
  _i3.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_9(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i3.RxString);

  @override
  int get totalOperations =>
      (super.noSuchMethod(Invocation.getter(#totalOperations), returnValue: 0)
          as int);

  @override
  int get successfulOperations =>
      (super.noSuchMethod(
            Invocation.getter(#successfulOperations),
            returnValue: 0,
          )
          as int);

  @override
  double get successRate =>
      (super.noSuchMethod(Invocation.getter(#successRate), returnValue: 0.0)
          as double);

  @override
  set isLoading(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(_i3.RxString? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  String getPerformanceStats() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceStats, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#getPerformanceStats, []),
            ),
          )
          as String);

  @override
  _i8.Future<void> addMember({
    required String? memberNumber,
    required String? fullName,
    String? idNumber,
    String? phoneNumber,
    String? email,
    String? gender,
    String? zone,
    double? acreage,
    int? noTrees,
    bool? isActive = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMember, [], {
              #memberNumber: memberNumber,
              #fullName: fullName,
              #idNumber: idNumber,
              #phoneNumber: phoneNumber,
              #email: email,
              #gender: gender,
              #zone: zone,
              #acreage: acreage,
              #noTrees: noTrees,
              #isActive: isActive,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateMember(_i6.Member? member) =>
      (super.noSuchMethod(
            Invocation.method(#updateMember, [member]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> activateMember(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#activateMember, [memberId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deactivateMember(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateMember, [memberId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteMember(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMember, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.Member?> getMemberByNumber(String? memberNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberByNumber, [memberNumber]),
            returnValue: _i8.Future<_i6.Member?>.value(),
          )
          as _i8.Future<_i6.Member?>);

  @override
  _i8.Future<List<_i6.Member>> getMembersByNumber(String? memberNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembersByNumber, [memberNumber]),
            returnValue: _i8.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i8.Future<List<_i6.Member>>);

  @override
  _i8.Future<_i6.Member?> getMemberByIdNumber(String? idNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberByIdNumber, [idNumber]),
            returnValue: _i8.Future<_i6.Member?>.value(),
          )
          as _i8.Future<_i6.Member?>);

  @override
  _i8.Future<List<_i6.Member>> getMembersByIdNumber(String? idNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembersByIdNumber, [idNumber]),
            returnValue: _i8.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i8.Future<List<_i6.Member>>);

  @override
  _i8.Future<Map<String, dynamic>> validateMemberData({
    required String? memberNumber,
    String? idNumber,
    String? excludeMemberId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateMemberData, [], {
              #memberNumber: memberNumber,
              #idNumber: idNumber,
              #excludeMemberId: excludeMemberId,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> findAllDuplicates() =>
      (super.noSuchMethod(
            Invocation.method(#findAllDuplicates, []),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  List<_i6.Member> searchMembers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMembers, [query]),
            returnValue: <_i6.Member>[],
          )
          as List<_i6.Member>);

  @override
  _i8.Future<List<_i6.Member>> quickSearchMembers(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#quickSearchMembers, [query], {#limit: limit}),
            returnValue: _i8.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i8.Future<List<_i6.Member>>);

  @override
  _i8.Future<List<_i6.Member>> importMembersFromExcel() =>
      (super.noSuchMethod(
            Invocation.method(#importMembersFromExcel, []),
            returnValue: _i8.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i8.Future<List<_i6.Member>>);

  @override
  _i8.Future<List<_i6.Member>> importMembersFromCsv() =>
      (super.noSuchMethod(
            Invocation.method(#importMembersFromCsv, []),
            returnValue: _i8.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i8.Future<List<_i6.Member>>);

  @override
  _i8.Future<void> exportMembersToExcel() =>
      (super.noSuchMethod(
            Invocation.method(#exportMembersToExcel, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> exportMembersToCsv() =>
      (super.noSuchMethod(
            Invocation.method(#exportMembersToCsv, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> downloadCsvTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#downloadCsvTemplate, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> downloadImportTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#downloadImportTemplate, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearAllCaches() => super.noSuchMethod(
    Invocation.method(#clearAllCaches, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> safeRefreshMembers() =>
      (super.noSuchMethod(
            Invocation.method(#safeRefreshMembers, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshMembers() =>
      (super.noSuchMethod(
            Invocation.method(#refreshMembers, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> forceCompleteRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#forceCompleteRefresh, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Disposer addListener(_i11.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i11.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i12.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Disposer addListenerId(Object? key, _i11.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i11.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Rx<_i6.User?> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeRx_5<_i6.User?>(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i3.Rx<_i6.User?>);

  @override
  _i3.RxBool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoggedIn)),
          )
          as _i3.RxBool);

  @override
  _i3.RxList<_i6.User> get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeRxList_11<_i6.User>(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i3.RxList<_i6.User>);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i4.AuthService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i4.AuthService>.value(
              _FakeAuthService_12(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i4.AuthService>);

  @override
  _i8.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.User> createUser({
    required String? username,
    required String? fullName,
    required _i6.UserRole? role,
    required String? email,
    String? phoneNumber,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #username: username,
              #fullName: fullName,
              #role: role,
              #email: email,
              #phoneNumber: phoneNumber,
              #password: password,
            }),
            returnValue: _i8.Future<_i6.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#createUser, [], {
                  #username: username,
                  #fullName: fullName,
                  #role: role,
                  #email: email,
                  #phoneNumber: phoneNumber,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.User>);

  @override
  _i8.Future<void> updateUser(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deactivateUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateUser, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool hasPermission(List<_i6.UserRole>? allowedRoles) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [allowedRoles]),
            returnValue: false,
          )
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
